/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AppsRouteImport } from './routes/apps'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesVocabflexRouteImport } from './routes/games/vocabflex'
import { Route as GamesReadflexRouteImport } from './routes/games/readflex'
import { Route as GamesPandANalogiesRouteImport } from './routes/games/pand-a-nalogies'
import { Route as GamesKpopWordWarriorRouteImport } from './routes/games/kpop-word-warrior'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRoute = AppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesVocabflexRoute = GamesVocabflexRouteImport.update({
  id: '/games/vocabflex',
  path: '/games/vocabflex',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesReadflexRoute = GamesReadflexRouteImport.update({
  id: '/games/readflex',
  path: '/games/readflex',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesPandANalogiesRoute = GamesPandANalogiesRouteImport.update({
  id: '/games/pand-a-nalogies',
  path: '/games/pand-a-nalogies',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesKpopWordWarriorRoute = GamesKpopWordWarriorRouteImport.update({
  id: '/games/kpop-word-warrior',
  path: '/games/kpop-word-warrior',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apps': typeof AppsRoute
  '/contact': typeof ContactRoute
  '/games/kpop-word-warrior': typeof GamesKpopWordWarriorRoute
  '/games/pand-a-nalogies': typeof GamesPandANalogiesRoute
  '/games/readflex': typeof GamesReadflexRoute
  '/games/vocabflex': typeof GamesVocabflexRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apps': typeof AppsRoute
  '/contact': typeof ContactRoute
  '/games/kpop-word-warrior': typeof GamesKpopWordWarriorRoute
  '/games/pand-a-nalogies': typeof GamesPandANalogiesRoute
  '/games/readflex': typeof GamesReadflexRoute
  '/games/vocabflex': typeof GamesVocabflexRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apps': typeof AppsRoute
  '/contact': typeof ContactRoute
  '/games/kpop-word-warrior': typeof GamesKpopWordWarriorRoute
  '/games/pand-a-nalogies': typeof GamesPandANalogiesRoute
  '/games/readflex': typeof GamesReadflexRoute
  '/games/vocabflex': typeof GamesVocabflexRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/apps'
    | '/contact'
    | '/games/kpop-word-warrior'
    | '/games/pand-a-nalogies'
    | '/games/readflex'
    | '/games/vocabflex'
    | '/api/public/contact'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/apps'
    | '/contact'
    | '/games/kpop-word-warrior'
    | '/games/pand-a-nalogies'
    | '/games/readflex'
    | '/games/vocabflex'
    | '/api/public/contact'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/apps'
    | '/contact'
    | '/games/kpop-word-warrior'
    | '/games/pand-a-nalogies'
    | '/games/readflex'
    | '/games/vocabflex'
    | '/api/public/contact'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppsRoute: typeof AppsRoute
  ContactRoute: typeof ContactRoute
  GamesKpopWordWarriorRoute: typeof GamesKpopWordWarriorRoute
  GamesPandANalogiesRoute: typeof GamesPandANalogiesRoute
  GamesReadflexRoute: typeof GamesReadflexRoute
  GamesVocabflexRoute: typeof GamesVocabflexRoute
  ApiPublicContactRoute: typeof ApiPublicContactRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/vocabflex': {
      id: '/games/vocabflex'
      path: '/games/vocabflex'
      fullPath: '/games/vocabflex'
      preLoaderRoute: typeof GamesVocabflexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/readflex': {
      id: '/games/readflex'
      path: '/games/readflex'
      fullPath: '/games/readflex'
      preLoaderRoute: typeof GamesReadflexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/pand-a-nalogies': {
      id: '/games/pand-a-nalogies'
      path: '/games/pand-a-nalogies'
      fullPath: '/games/pand-a-nalogies'
      preLoaderRoute: typeof GamesPandANalogiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/kpop-word-warrior': {
      id: '/games/kpop-word-warrior'
      path: '/games/kpop-word-warrior'
      fullPath: '/games/kpop-word-warrior'
      preLoaderRoute: typeof GamesKpopWordWarriorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppsRoute: AppsRoute,
  ContactRoute: ContactRoute,
  GamesKpopWordWarriorRoute: GamesKpopWordWarriorRoute,
  GamesPandANalogiesRoute: GamesPandANalogiesRoute,
  GamesReadflexRoute: GamesReadflexRoute,
  GamesVocabflexRoute: GamesVocabflexRoute,
  ApiPublicContactRoute: ApiPublicContactRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
